name: Release Build

on:
  release:
    types: [ created ]

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build plugin
        run: ./gradlew clean :buildPlugin -Pversion=SNAPSHOT-${{ github.run_number }}

      - name: Upload plugin archive
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}