name: Release Build

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scripts
        run: |
          python project-scripts/minify_scripts.py
          python project-scripts/update_stubs.py

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Build plugin
        run: ./gradlew clean :buildPlugin -Pversion=${{ github.ref_name }}

      - name: Upload plugin to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}